spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
    username: root
    password:
  h2:
    console:
      enabled: true
logging:
  level:
    org.springframework.boot.web: DEBUG
    org.springframework.web: DEBUG
    Exposed: DEBUG
    sample: DEBUG
